### PR TITLE
Add pyreact with jsx

### PR DESCRIPTION
**Pull request by chompomonim**
FrontPage with sortable list of fractions and parliamentarians.

### CODE REVIEW

**Comment by frgtn** [comment]
We're missing Makefile directives to set up nodejs things from 8749cc09916fbaa239dd44b0324f21c730e8dd03. Will add it.

**Comment by chompomonim** [comment]
We don't need nodejs anymore! We use CDN for ReacJs

**Comment by frgtn** [comment]
You're right, we really don't need it. I thought pyreact depended on node and react being installed for server-side JSX transforms.

**Comment by frgtn** [comment]
Lets
ship it

**Pull request merged**
