### PR TITLE
Handle dash-separated last names

### PR DESCRIPTION
**Pull request by frgtn**
Adds a special case to normalize dash-separated surnames. This is needed because some MPs have their double surnames separated by a space in lrs.lt profiles but dash-separated in transcripts.

Also added a few changes to make it easier to develop Manoseimas on OSX.

### CODE REVIEW

**Comment by chompomonim** [comment]
Would you also mind to update documentation with MacOSX instructions?

And of course fix tests ;)

**Comment by frgtn** [comment]
@chompomonim that same test is also failing on master. I don't have the bandwidth to look into why that's happening right now, sorry.

**Comment by frgtn** [comment]
Updated `HACKING.rst` with OSX setup instructions.

**Comment by chompomonim** [comment]
Very strange. It doesn't fail on my machine :/

**Pull request merged**
